use master
Drop database EcmMobileShop
go
CREATE DATABASE EcmMobileShop
go
use EcmMobileShop
go

CREATE TABLE tb_HANGSP (
IdHangSP int identity(1,1) primary key,
TenHangSP nvarchar(100),
TrangThai bit NOT NULL DEFAULT 1,
)
go
CREATE TABLE tb_LOAISP (
IdLoaiSP int identity(1,1) primary key,
TenLoaiSP nvarchar(100),
TrangThai bit NOT NULL DEFAULT 1,
)
go
create table tb_MAUSAC(
IdMau int identity(1,1) primary key,
MaMau nvarchar(20),
TenMau nvarchar(20)
)
go
CREATE TABLE tb_SANPHAM (
IdSP int identity(1,1) primary key,
IdHangSP int,
IdLoaiSP int,
TenSP nvarchar(200),
MoTaSP nvarchar(max),
Gia float,
ImagePathMain nvarchar(max), 
NgayNhap datetime,
TrangThai bit NOT NULL DEFAULT 1,
constraint fk_tb_SANPHAM_tb_HANGSP foreign key(IdHangSP) references tb_HANGSP(IdHangSP),
constraint fk_tb_SANPHAM_tb_LOAISP foreign key(IdLoaiSP) references tb_LOAISP(IdLoaiSP),
)
go
CREATE TABLE tb_CT_SANPHAM (
IdctSP int identity(1,1) primary key,
IdSP int,
SoLuongSP int,
IdMau int not null,
ImagePathDetail nvarchar(max),
constraint fk_tb_CT_SANPHAM_tb_MAUSAC foreign key(IdMau) references tb_MAUSAC(IdMau),
constraint fk_tb_CT_SANPHAM_tb_SANPHAM foreign key(IdSP) references tb_SANPHAM(IdSP),
)
go
CREATE TABLE tb_KHACHHANG (
IdKH int identity(1,1) primary key,
TenKH nvarchar(50),
DiaChi nvarchar(100),
SDT nchar(11),
TrangThai bit NOT NULL DEFAULT 1,
)
go
create table tb_TINHTRANGDH(
IdTinhTrangDH int identity(1,1) primary key,
TenTinhTrang nvarchar(100),
)
go
CREATE TABLE tb_HOADON (
IdHD int identity(1,1) primary key,
IdTinhTrangDH int,
IdKH int,
DiaChiGiao nvarchar(100),
NgayLap datetime,
constraint fk_KH_HD foreign key(IdKH) references tb_KHACHHANG(IdKH),
constraint fk_TT_HD foreign key(IdTinhTrangDH) references tb_TinhTrangDH(IdTinhTrangDH)
)
go
CREATE TABLE tb_CHITIETHOADON (
IdctHD int identity(1,1) primary key,
IdHD int,
IdctSP int,
TenSP nvarchar(200),
SoLuongBan float,
GiaBan float,
constraint fk_HD_CTHD foreign key(IdHD) references tb_HOADON(IdHD),
constraint fk_ctSP_CTHD foreign key(IdctSP) references tb_CT_SANPHAM(IdctSP)
)
go
CREATE TABLE tb_FEEDBACK (
IdFB int identity(1,1) primary key,
IdctHD int not null,
Noidung nvarchar(500) not null,
Img nvarchar(max),
NgayFB datetime,
constraint fk_CTHD_FB foreign key(IdctHD) references tb_CHITIETHOADON(IdctHD),
)
go
CREATE TABLE tb_DISCOUNTSP (
IdDCSP int identity(1,1) primary key,
IdSP int not null,
GiaTri float not null,
NgayHH datetime,
TinhTrang bit NOT NULL DEFAULT 1,
constraint fk_SP_DC foreign key(IdSP) references tb_SANPHAM(IdSP),
)
go
CREATE TABLE tb_DISCOUNTKH (
IdDCKH int identity(1,1) primary key,
IdKH int not null,
GiaTri float not null,
NgayHH datetime,
TinhTrang bit NOT NULL DEFAULT 1,
constraint fk_KH_DC foreign key(IdKH) references tb_KHACHHANG(IdKH),
)
go
CREATE TABLE tb_Banner (
IdBanner int identity(1,1) primary key,
NgayHH datetime,
ImagePathDetail nvarchar(max) not null,
TinhTrang bit NOT NULL DEFAULT 1,
)
go
CREATE TABLE tb_BannerSP (
IdBannerSP int identity(1,1) primary key,
IdSP int not null,
NgayHH datetime,
TinhTrang bit NOT NULL DEFAULT 1,
ImagePathDetail nvarchar(max) not null,
constraint fk_SP_BannerSP foreign key(IdSP) references tb_SANPHAM(IdSP),
)
go
CREATE TABLE tb_DISCOUNTTIME (
IdDCTime int identity(1,1) primary key,
NgayHH datetime,
TinhTrang bit NOT NULL DEFAULT 1,
)
go
CREATE TABLE tb_YKIEN (
IdYK int identity(1,1) primary key,
SDT nchar(11),
email nvarchar(100),
NgayYKien datetime,
NoiDung nvarchar(500),
)
go
insert into tb_LOAISP(TenLoaiSP)
values
(N'Tai Nghe'),
(N'Loa'),
(N'Máy ảnh'),
(N'Máy tính và Laptop'),
(N'Điện thoại'),
(N'Máy phát nhạc'),
(N'Chuột máy tính'),
(N'Điều khiển game'),
('Pin dự phòng'),
(N'Đồng hồ'),
(N'Tablet')
GO
insert into tb_HANGSP(TenHangSP)
values 
('Philips'),
('Huawei'),
('Apple'),
('Sony'),
('Unihertz'),
('Canon'),
('Samsung'),
('Lenovo'),
('ednet GmbH'),
('iRiver'),
('Transcend Information'),
('Xiaomi'),
('Rapoo Technology'),
('Nokia'),
('Gembird Europe BV'),
('Speedlink'),
('Bo'),
('Asus')
GO
insert into tb_TinhTrangDH(TenTinhTrang) values (N'Đã đặt hàng')
insert into tb_TinhTrangDH(TenTinhTrang) values (N'Đã xác nhận')
insert into tb_TinhTrangDH(TenTinhTrang) values (N'Đã thanh toán')
insert into tb_TinhTrangDH(TenTinhTrang) values (N'Đang được giao')
insert into tb_TinhTrangDH(TenTinhTrang) values (N'Hoàn thành')
insert into tb_TinhTrangDH(TenTinhTrang) values (N'Đã Huỷ')
go
insert into tb_SANPHAM (TenSP,IdHangSP, IdLoaiSP, Gia, ImagePathMain, MoTaSP)
values 
('Philips BT6900A',1,2, 225, 'https://f8-zpcloud.zdn.vn/1498056500057927627/46b2e8397b81a6dfff90.jpg',N'Loa philips BT6900A dùng để phát nhạc'),
('Huawei MediaPad',2,6, 225, 'https://f9-zpcloud.zdn.vn/9089540525722719989/28406a71c2c91f9746d8.jpg',N'Huawei MediaPad dùng để nghe nhạc, chơi game và nhiều chức năng khác'),
('Apple iPod shuffle',3,6,379,'https://f8-zpcloud.zdn.vn/3905040690467303925/9cabc1cf6b77b629ef66.jpg',N'Máy Apple iPod shuffle dùng để nghe nhạc'),
('Sony MDRZX310W',4,1, 225, 'https://f9-zpcloud.zdn.vn/8850552338859793538/960b82f5294df413ad5c.jpg',N'Tai nghe Sony dùng để nghe nhạc'),
('LUNA Smartphone',5,5, 379, 'https://f8-zpcloud.zdn.vn/6890547260255790327/3e13931e3da6e0f8b9b7.jpg',N'Smartphone Luna dùng để gọi và các chức năng khác'),
('Canon IXUS 175',6,3,379, 'https://f9-zpcloud.zdn.vn/4331014760625145716/091ef71e56a68bf8d2b7.jpg',N'Canon IXUS 175 dùng để chụp hình'),
('Canon STM Kit',6,3,379, 'https://f9-zpcloud.zdn.vn/3516845691762163440/b4c835b890004d5e1411.jpg',N'Canon STM Kit dùng để chụp hình'),
('Samsung J330F',7,5, 225, 'https://f9-zpcloud.zdn.vn/4964687665886756019/b0de9b4e23f6fea8a7e7.jpg',N'Smartphone Samsung J330F dùng để để gọi và các chức năng khác'),
('Lenovo IdeaPad',8,11,225, 'https://f9-zpcloud.zdn.vn/1982473211109659255/dae1e85851e08cbed5f1.jpg',N'Laptop Lenovo thích hợp cho văn phòng'),
('Digitus EDNET',9,9,379, 'https://f8-zpcloud.zdn.vn/4698635953048460420/1bdcf7934c2b9175c83a.jpg',N'Pin dự phòng Ednet có thể chứa 5000mAh'),
('Astro M2 Black',10,6,225, 'https://f8-zpcloud.zdn.vn/3962378003029983750/bbe1c3707fc8a296fbd9.jpg',N'Máy Astro M2 Black dùng để nghe nhạc'),
('Transcend T.Sonic',11,6,225, 'https://f8-zpcloud.zdn.vn/4234069458252406000/ba417885c43d1963402c.jpg',N'Máy Astro M2 Black dùng để nghe nhạc'),
('Xiaomi Band 2',12,10,225, 'https://f9-zpcloud.zdn.vn/4788716100702118287/ed62405efee623b87af7.jpg',N'Đồng hồ Xiaomi dùng để theo dõi sức khỏe'),
('Rapoo T8 White',13,7,379, 'https://f9-zpcloud.zdn.vn/8889816080986219893/a831f0254f9d92c3cb8c.jpg',N'Chuột máy tính Rapoo di chuyển rất mượt'),
('Nokia 3310 (2017)',14,5, 379, 'https://f8-zpcloud.zdn.vn/251579608831398292/ea4e22a893104e4e1701.jpg',N'Nokia 3310 dùng để gọi và các chức năng khác'),
('Rapoo 7100p Gray',13,7, 225, 'https://f8-zpcloud.zdn.vn/4130890314513558525/6f1e8fe53d5de003b94c.jpg',N'Chuột máy tính Rapoo di chuyển rất mượt'),
('Canon EF',6,3,379, 'https://f8-zpcloud.zdn.vn/8054836897786462932/8e2c9e232a9bf7c5ae8a.jpg',N'Canon EF dùng để chụp hình'),
('Gembird SPK-103',15,2,225, 'https://f8-zpcloud.zdn.vn/357883875769593643/8a01236a96d24b8c12c3.jpg',N'Loa Gembird dùng để phát nhạc'),
('Sony PS4 Slim',4,8,300,'https://f9-zpcloud.zdn.vn/607005283512847213/c0af45b31387cfd99696.jpg',N'Máy PS4 dùng để giải trí'),
('Speedlink',16,8,375, 'https://f10-zpcloud.zdn.vn/6483442226326085064/b04ae57e8d4a5114085b.jpg',N'Điều khiển Speedlink dùng để giải trí'),
('Beoplay H7',17,1,300, 'https://f10-zpcloud.zdn.vn/7096629597012267425/fa44feed94d9488711c8.jpg',N'Tai nghe Beoplay dùng để nghe nhạc')
GO
Insert into tb_MAUSAC(MaMau,TenMau)
values
('#ffd60a', N'Vàng'),
('#ef233c', N'Đỏ'),
('#003566', N'Xanh'),
('#ffb4a2', N'Magenta'),
('#000814', N'Đen'),
('#ffffff', N'Trắng'),
('#48cae4', N'Lam'),
('#e76f51', N'Cam'),
('#ddbea9', N'Nâu'),
('#ced4da', N'Xám'),
('#dee2ff', N'Tím'),
('#d9ed92', N'Xanh lá'),
('#52b788', N'Lục'),
('#b5ffe1', N'Mint'),
('#ff5d8f', N'Hồng')
GO
insert into tb_SANPHAM (TenSP,IdHangSP, IdLoaiSP, Gia, ImagePathMain, MoTaSP)
values
(N'Asus TUF Dash F15','18','4','899','https://f9-zpcloud.zdn.vn/7402776772003405611/a77cd00ee5aa39f460bb.jpg',
N'Laptop Asus TUF Gaming F15 FX506HC-HN144W sở hữu thiết kế táo bạo và độc đáo bậc nhất trên thị trường với gam màu Graphite black nổi bật mà cực huyền bí. Với hiệu năng đỉnh cao và linh kiện cấu thành có chất lượng đứng đầu thị trường, chiếc laptop Asus Gaming này được kỳ vọng dễ dàng chinh phục mọi thử thách và đồng hành với các game thủ trên mọi đấu trường.'),
(N'Zenfone 8','18','5','449','https://f9-zpcloud.zdn.vn/1392972853555413887/547d3a1074b4a8eaf1a5.jpg',
N'The mighty Zenfone 8 packs superb performance into a compact easy-to-handle package, combining effortless operation with perfect pocketability. You also get the latest Qualcomm® Snapdragon™ 888 5G Mobile Platform for top-notch performance, an ultra-clear 120 Hz AMOLED display with breathtaking visuals, a long-lasting 4000 mAh battery for non-stop work or play, and a pro-grade camera system with Sony sensors. Zenfone 8 performs great, looks great, and feels great!'),
(N'Galaxy M52 G5','7','5','398','https://f10-zpcloud.zdn.vn/1117554255534553121/82f2daca2470f82ea161.jpg',
N'Điện thoại Samsung M52 nổi bật trong mắt người dùng đến từ thiết kế sang trọng nhưng gói gọn trong phân khúc tầm trung – giá rẻ. Bên cạnh đó, các góc và các cạnh được làm bo cong nhẹ để giúp cầm tốt hơn, không bị trơn tuột như trên mặt kính hay nhựa. Samsung Galaxy M52 sử dụng màn hình kích thước 6.7 inches, cùng với tấm nền sAMOLED cho khả năng hiển thị rực rỡ hơn nhiều so với màn FullHD. Bên cạnh đó, màn hình đã vận dụng màn dạng đục lỗ, giúp mở rộng được kích thước không gian trải nghiệm. Và độ phân giải đạt chuẩn FullHD cho khả năng hiển thị sắc nét, góc nhìn tốt.'),
(N'Mac Air M2','3','4','598','https://f9-zpcloud.zdn.vn/5710158458298506411/b184c00f35b5e9ebb0a4.jpg',
N'Macbook Air 2022 được thiết kế mỏng nhẹ với trọng lượng 1.24 kg. Toàn bộ phần vỏ vẫn được giữ nguyên chất liệu nhôm cứng cáp, bền bỉ nên vẫn thể hiện được sự sang trọng và đẳng cấp. Bên cạnh đó, các cạnh bo tròn mềm mại cùng được vát mỏng mang đến một tổng thể tuyệt mỹ và vô cùng gọn gàng. Trên Macbook Air 2022 này, Apple sẽ trang bị cho máy màn hình Liquid Retina kích thước 13.6 inch, hỗ trợ đến 1 tỷ màu. Bên cạnh đó là độ sáng 500 nits, dải màu rộng P3 cùng công nghệ True Tone. Nhờ vậy mà hình ảnh hiển thị sống động, rực rỡ, độ tương phản phong phú, chi tiết sắc nét hơn rất nhiều. Đây được đánh giá là màn hình lớn và sáng nhất so với các thế hệ Macbook Air trước đây.'),
(N'Airpod Pro 2021','3','1','449','https://f10-zpcloud.zdn.vn/2317775434085282861/1f98d846ef1d3043690c.jpg',
N'Trên Macbook Air 2022 này, Apple sẽ trang bị cho máy màn hình Liquid Retina kích thước 13.6 inch, hỗ trợ đến 1 tỷ màu. Bên cạnh đó là độ sáng 500 nits, dải màu rộng P3 cùng công nghệ True Tone. Nhờ vậy mà hình ảnh hiển thị sống động, rực rỡ, độ tương phản phong phú, chi tiết sắc nét hơn rất nhiều. Đây được đánh giá là màn hình lớn và sáng nhất so với các thế hệ Macbook Air trước đây.'),
(N'Galaxy Buds','7','1','449','https://f9-zpcloud.zdn.vn/2834839670771416712/3c85b9bbe2e03dbe64f1.jpg',
N'Samsung Galaxy Buds không có quá nhiều đột phá về thiết kế nhưng chất lượng hoàn thiện của Samsung trên sản phẩm này đã tốt hơn rất nhiều. Bộ đôi tai nghe này không có phím vật lý. Sản phẩm mới của Samsung cũng có thiết kế rất nhỏ gọn, tinh tế nhưng cũng không kém phần chắc chắn. Thiết kể nhỏ gọn cùng với trọng lượng chỉ 5.6 gram, SS Galaxy Buds không hề tạo cảm giác khó chịu, bất tiện khi sử dụng. Samsung đã có một bước tiến lớn về khả năng hoàn thiện sản phẩm.'),
(N'Tai nghe Sony WH-1000XM4','4','1','449','https://f9-zpcloud.zdn.vn/55796585499311416/eae3974dc5161a484307.jpg',
N'Sony WH-1000XM4 được trang bị khả năng phân tích và điều khiển thời gian thực. Nhờ đó giúp tai nghe chụp tai WH-1000MX4 luôn phân tích các tiếng ồn xung quanh và điều chỉnh mức độ chống ồn nhằm mang lại cho người dùng âm thanh chất lượng tốt nhất.'),
(N'Tai nghe Sony WF','4','1','449','https://f9-zpcloud.zdn.vn/7531990554745330401/0f0ea62af0712f2f7660.jpg',
N'Tai nghe Sony WF-1000XM4 gây ấn tượng với người dùng bởi khả năng chống ồn cực kỳ hiệu quả, thứ đã làm nên thương hiệu của Sony. Tất cả là nhờ vào bộ xử lý tích hợp V1 với công nghệ cảm biến tiếng ồn kép thu tiếng ồn môi trường xung quanh. Sau đó, kết hợp với thuật toán mới của hãng thì nó sẽ cho ra khả năng chống ồn tương ứng với đa dạng môi trường.'),
(N'Galaxy Buds Pro','7','1','449','https://f9-zpcloud.zdn.vn/2113166615008528448/14e508f769acb6f2efbd.jpg',
N'Samsung Galaxy Buds Pro sở hữu một thiết kế bầu dục, khác với thiết kế bo tròn trên thế hệ tiền nhiệm. Được phủ thêm một lớp sơn bóng giúp làm nổi bật thiết kế của tai nghe thêm phần bắt mắt, nổi bật dưới mọi góc nhìn.'),
(N'Tai nghe Xiaomi','12','1','449','https://f9-zpcloud.zdn.vn/3888277398863520071/45bd9054ec0f33516a1e.jpg',
N'Tai nghe Xiaomi Buds 3 được trang bị công nghệ chống ồn chủ động giúp loại bỏ những tiếng ồn đến từ môi trường xung quanh. Cụ thể, tai nghe hộ trợ loại bỏ những tiếng ồn không mong muốn với âm thanh lên đến 40 dB, nhờ đó có thể loại bỏ được tới 99% tạp âm. Tính năng thông minh này giúp người dùng có thể tận hưởng các giải trí âm thanh kể cả ở những nơi ồn ào như xe bus, bến xe,...'),
(N'Tai nghe Xiaomi Mi Capsule','12','1','190','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/c/a/capsule_den.jpg',
N'Điểm nổi bật nhất đối với Xiaomi Mi Capsule chắc chắn chính là ngoại hình mà nó sở hữu. Khó có thể kiếm cho chúng ta thấy được một bản phẩm tai nghe đặc biệt như vậy trên thị trường Việt Nam hiện nay. Với kích thước to hơn viên thuốc một chút với hai đầu được bo tròn và sử dụng hai màu khác nhau khiến cho chiếc tai nghe có dây này trở nên vô cùng khác biệt so với các thiết kế trên thị trường.'),
(N'Xiaomi 13 8GB 256GB','12','5','350','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/p/m/pms_1670745783.80967984.png',
N'Xiaomi 13 mang giao diện ưa nhìn, mang nét sang trọng, pha một chút thanh lịch, với các chi tiết được hoàn thiện tỉ mỉ đẹp mắt. Các góc cạnh vuông tinh tế, mặt lưng từ chất liệu polymer silicon kết hợp công nghệ nano-skin giúp chống trầy xước, bụi bẩn. Đồng thời mặt sau thiết kế cụm camera ở góc trên cùng bên trái màn hình.'),
(N'Đồng hồ Xiaomi Watch S1 Pro','12','10','379','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/1/_/1_245_2.jpg',
N'Đồng hồ Xiaomi Watch S1 Pro là dòng sản phẩm đồng hồ thông minh nâng cấp dành cho phiên bản Xiaomi Watch S1. Nhờ vào thiết kế độc đáo, chắc chắn cùng nhiều tính năng tuyệt vời, chiếc đồng hồ chắc chắn là lựa chọn đáng tham khảo.'),
(N'Samsung Galaxy Watch5','7','10','249','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/s/a/sansung_1__2.png',
N'Đồng hồ thông minh Samsung Galaxy Watch 5 với mặt đồng hồ tròn thường thấy trên các mẫu trước đó. Thiết kế này đem đến cho thiết bị sự hiện đại, trẻ trung cùng sự tiện lợi khi bạn sử dụng thiết bị. Bên cạnh đó, màn hình tinh thể Sapphire mới nhất đem đến khả năng chống trầy xước, chống bụi cực tốt, gấp 1.6 lần so với thế hệ Watch 4 trước đó. Vòng xoay benzen thế hệ cũ sẽ được lược bỏ, thay vào đó là thao tác điều hướng vào nút bấm cạnh phải và màn hình cảm ứng. Khung viền chất liệu Armor Aluminum chắc chắn, dạng mờ, góp phần nâng cao tính thẩm mỹ, sự sang trọng và tinh xảo của sản phẩm. Màn hình kích thước 1.2 inch cùng trọng lượng 28.7g gọn nhẹ. Độ phân giải cao cùng mật độ điểm ảnh chuẩn 330 PPI. Bạn hoàn toàn có thể tự tin thể hiện cá tính với màu sắc trẻ trung, nổi bật: Xám Graphite, Hồng vàng và Bạc. Ngoài ra, Watch5 trang bị bộ nhớ trong 16GB và RAM 1.5 GB, cho khả năng đa nhiệm, lưu trữ ổn định và phát nhạc offline.'),
(N'Smart Watch Huawei Band 7','2','10','300','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/s/m/smart_band.png',
N'Đồng hồ thông minh Huawei sở hữu thiết kế công thái học giúp tổng thể trông hấp dẫn và bắt mắt. Các màu sắc phiên bản hợp thời trang gây cảm tình với bất cứ ai vô tình trông thấy. Kích thước màn hình Huawei Band 7 nhỏ gọn khoảng 1,47 inch, trang bị tấm nền Amoled có cảm biến giúp hình ảnh hiển thị luôn sắc nét sống động và vô cùng ấn tượng. Đồng hồ được trang bị chuẩn chống nước 5 ATM nhờ đó bạn không cần lo lắng khi sử dụng smartwatch bên ngoài.'),
(N'Apple Watch SE 2022','3','10','249','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/a/p/apple_lte_13_.png',
N'Apple Watch SE 2022 44mm GPS lần này vẫn là một tái thiết kế mang đầy nét riêng và quen thuộc vốn có của những chiếc Apple Watch nhà Táo – “Planet in mind- Thiết kế mặt lưng ”. Bên cạnh đó việc được thiết kế với mặt đồng hồ khá lớn lên đến 44mm cũng cho phép người dùng tăng được sự thoải mái trải nghiệm trên chiếc đồng hồ này. Với ba màu sắc dự kiến ra mắt Midnight, Starlight, Silver kết hợp cùng phần thiết kế mang hơi hướng trẻ trung, hiện đại và phù hợp với giới trẻ thì chắc chắn Apple Watch SE 2022 44mm GPS sẽ lại là cơn sóng mới trong dòng đồng hồ thông minh của năm nay.'),
(N'MacBook Pro 2023','3','4','479','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/m/2/m2_pro_14.png',
N'Macbook Pro 14 inch 2023 sở hữu cho mình thiết kế màn hình kích thước rộng 14 inch vô cùng thoải mái, viền vô cùng mỏng. Giúp cho người dùng được trải nghiệm phần nhìn được tốt hơn, người dùng có thể sử dụng nhiều tác vụ cùng một lúc, tăng hiệu suất công việc, học tập. Hỗ trợ True Tone cùng dải màu P3 giúp cho hình ảnh hiển thị vô cùng sắc nét, các màu sắc sáng, tối được thể hiện chi tiết hơn. Độ phân giải 3.024 x 1.964 cùng độ sáng tối đa là 1.600 nit, giúp cho mắt của chúng ta không bị quá khó chịu.'),
(N'Galaxy Z Flip4','7','5','379','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/f/l/flip4-xanh.png',
N'Điện thoại Samsung ZFlip 4 tiếp tục là một mẫu mã sang chảnh, thời thượng của Samsung được lấy cảm hứng từ hộp trang điểm cầm tay của các chị em hay chiếc vỏ sò. Với công nghệ gập đột phá, Samsung đã tạo ra một chiếc smartphone mang đậm dấu ấn Samsung trên thị trường. Đóng lại là phụ kiện công nghệ với kích thước 4.2-inch, vừa vặn mọi ngăn túi. Mở ra là một chiếc smartphone gập phá vỡ mọi giới hạn từ trước đến nay. Điện thoại Samsung ZFlip 4 tiếp tục là một mẫu mã sang chảnh, thời thượng của Samsung được lấy cảm hứng từ hộp trang điểm cầm tay của các chị em hay chiếc vỏ sò. Với công nghệ gập đột phá, Samsung đã tạo ra một chiếc smartphone mang đậm dấu ấn Samsung trên thị trường. Đóng lại là phụ kiện công nghệ với kích thước 4.2-inch, vừa vặn mọi ngăn túi. Mở ra là một chiếc smartphone gập phá vỡ mọi giới hạn từ trước đến nay.'),
(N'iPhone 11 64GB','3','5','150','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/6/_/6_130.jpg',
N'Hiện tại, iPhone 11 vẫn được các chuyên gia đánh giá rất cao về độ ổn định của cấu hình trong thời gian dài sử dụng cũng như độ sắc nét mượt mà của màn hình trong các tác vụ như xem phim, chơi game. Về thiết kế bên ngoài, sản phẩm cũng vẫn luôn nhận được những phản hồi tích cực về sự bền bỉ, chắc chắn, cho cảm giác cầm nắm thoải mái, vừa tay. Bên cạnh đó, iPhone 11 còn sở hữu hệ thống máy ảnh có độ phân giải cao, đem lại cho người sử dụng những trải nghiệm quay chụp có độ sắc nét và cực kỳ sống động. Điểm yếu của dòng sản phẩm này có lẽ nằm ở thời lượng Pin vẫn còn hạn chế, chưa mang lại trải nghiệm sử dụng tốt nhất. Tuy nhiên, điều này cũng đã được khắc phục thông qua công nghệ sạc nhanh 18W - Power Delivery 2.0 của Apple.'),
(N'Galaxy S22','7','5','290','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/s/m/sm-s901_galaxys22_front_green_211123.jpg',
N'Điện thoại Samsung Galaxy S22 sở hữu thiết kế nguyên khối cứng cáp và bền bỉ tuy nhiên mỏng hơn người đàn anh tiền nghiệm của mình là Galaxy S21. Tuy nhiên các đường nét thiết kế được thừa hưởng vẫn không khác nhau là mấy. Các chi tiết được hoàn thiện tỉ mỉ chính xác và trau chuốt từng góc cạnh mang lại một tổng thể sang trọng bắt mắt và tinh tế. Mặt lưng có thiết kế bóng bẩy dễ dàng thu hút người dùng ngay từ cái nhìn đầu tiên nhìn vào Samsung S22 phiên bản tiêu chuẩn này.'),
(N'Galaxy S22 Ultra','7','5','350','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/s/m/sm-s908_galaxys22ultra_front_green_211119.jpg',
N'Samsung Galaxy S22 Ultra đi theo ngôn ngữ thiết kế nguyên khối - kính cao cấp và sang trọng, vốn đã làm nên sự thành công của model tiền nhiệm. Chiếc máy có thiết kế mặt lưng đơn sắc tối giản nhưng không kém phần tinh tế, và màn hình tràn viền bao phủ gần như trọn mặt trước, tạo nên trải nghiệm quan sát rộng rãi trên một thiết bị di động nhỏ gọn vừa tay cầm. Độ bền của máy được đảm bảo tối ưu không chỉ qua lớp vỏ nhôm nguyên khối Amor đánh bóng, mà còn qua kính cường lực Corning Gorilla Glass Victus+ bao phủ hai mặt trước và sau. Khung nhôm và kính hoạt động như bộ giáp bảo vệ điện thoại an toàn. Chiếc máy còn có khả năng chống bụi / nước đạt chuẩn IP68 giúp người dùng luôn an tâm khi dùng máy trong những điều kiện môi trường khác nhau.'),
(N'Galaxy S20 FE','7','5','270','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/s/a/samsung-galaxy-20-fe_3_.jpg',
N'Trái tim của Galaxy S20 FE chính là bộ vi xử lý Snapdragon 865 8 nhân giúp máy hoạt động mạnh mẽ, nhưng vẫn tiết kiệm được pin nhờ áp dụng tiến trình sản xuất nhỏ hơn. Ngoài ra chuẩn bộ nhớ UFS 3.1 mới nhất cho tốc độ đọc ghi lần lượt là 2100Mb/s, 1200Mb/s. Ấn tượng nhất trong phân khúc các điện thoại đầu bảng hiện này, giúp Samsung Galaxy S20 Fan Edition có thể load các ứng dụng hay trao đổi file trên máy tính nhanh chóng hơn.'),
(N'Xiaomi Redmi Note 12','12','5','150','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/g/t/gtt_7766_3__1.jpg',
N'Xiaomi Redmi Note 12 sở hữu màn hình Super AMOLED với tần số quét 120Hz giúp trải nghiệm chạm vuốt diễn ra mượt mà, camera AI 50MP chất lượng. Bên cạnh đó, điện thoại sẽ được chạy trên con chip Qualcomm Snapdragon 685 kết hợp với card đồ họa GPU Qualcomm Adreno 610 mang lại trải nghiệm dùng ổn định. Điện thoại Xiaomi Redmi Note 12 mang lại thời gian sử dụng vượt trội với viên pin 5000mAh cùng sạc nhanh công suất 33W.'),
(N'Xiaomi Redmi Note 12 Pro 5G','12','5','370','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/g/t/gtt7766.jpg',
N'Xiaomi Redmi Note 12 Pro sở hữu cấu hình vượt trội gồm chip MediaTek Dimensity 1080, hệ thống ba camera với cảm biến chính 50MP và mạng 5G. Ngoài ra, màn hình Note 12 Pro 5G có kích thước khá lớn khoảng 6.67 inch, tấm nền AMOLED, tần số quét 120Hz khiến chiếc điện thoại nổi bật trong tầm giá dưới 8 triệu.'),
(N'Xiaomi 13 8GB 256GB','12','5','450','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/p/m/pms_1670745783.80967984.png',
N'Xiaomi 13 là sản phẩm mới được trang bị màn hình OLED kích thước 6.36 inch cùng tần số quét lên đến 120Hz. Bên trong Xiaomi 13 là con chip Snapdragon 8 Gen 2 mới nhất cùng bộ nhớ RAM 8GB vượt trội. Điện thoại cũng đáp ứng tốt khả năng nhiếp ảnh với camera Leica 50MP.'),
(N'Xiaomi Redmi Note 11 128GB','12','5','150','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/8/0/800x800-640x640-5.png',
N'Xiaomi Redmi Note 11 phiên bản 4GB/128GB được trang bị bộ vi xử lý Snapdragon 680 cùng viên pin 5.000 mAh sạc nhanh 33W. Điện thoại sở hữu bộ tứ camera bao gồm cảm biến chính độ phân giải 50MP, ống kính góc siêu rộng 8MP, camera macro 2MP và cảm biến đo độ sâu trường ảnh 2MP.'),
(N'Xiaomi Redmi Note 11 Pro','12','5','220','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/t/_/t_i_xu_ng_2__3_9.png',
N'Xiaomi Redmi Note 11 Pro là sản phẩm smartphone giá rẻ của thương hiệu Xiaomi. Điện thoại sở hữu màn hình AMOLED kích thước 6.67 inch cùng độ phân giải FHD+ giúp các chi tiết hiển thị rõ nét. Bên cạnh đó, thiết bị còn được trang bị con chip MediaTek Helio G96 cùng bộ nhớ RAM 8GB giúp mang lại khả năng hoạt động ổn định và mượt mà.'),
(N'Xiaomi 13 Lite','12','5','230','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/v/v/vvfrhgt77777_3_.jpg',
N'Xiaomi 13 Lite nổi bật nhờ cấu hình mạnh với chip Snapdragon 7 Gen 1, RAM 8GB LPDDR4x, ROM 256 GB. Ngoài ra, Mi 13 Lite còn sở hữu màn hình Full HD+ AMOLED 6.55 inch, tần số quét 120 Hz, phần khuyết đục lỗ chứa 2 camera selfie 32 MP.'),
(N'Xiaomi 12T','12','5','300','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/x/i/xiaomi-12t-xanh_1.jpg',
N'Xiaomi 12T là sản phẩm được nhiều tín đồ công nghệ đánh giá cao với màn hình AMOLED 6.67 inch độ phân giải cao, tần số quét 120Hz, chip MediaTek Dimensity 8100-Ultra, RAM 8GB và bộ nhớ trong 128GB. Thêm vào đó camera chính 108MP hỗ trợ chống rung OIS và sạc nhanh 120W cho trải nghiệm sử dụng cực chất.'),
(N'Xiaomi 13 Pro 12GB 256GB','12','5','470','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/1/3/13_prooo_3_.jpg',
N'Xiaomi 13 Pro là mẫu flagship mới sở hữu màn hình OLED 6.7 inch cùng tần số quét lên tới 120 Hz. Điện thoại sở hữu một cấu hình vượt trội với con chip Snapdragon gen 2 thế hệ mới, viên pin 4800 mAh hỗ trợ sạc nhanh công suất 120W. Camera máy mang lại cho người dùng khả năng nhiếp ảnh chuyên nghiệp với cụm camera Leica 50MP.'),
(N'Xiaomi 12T Pro','12','5','370','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/x/i/xiaomi-12t-xam_2.jpg',
N'Xiaomi Mi 12T Pro sở hữu vi xử lý Snapdragon 8 Gen 1+ mạnh mẽ, RAM 12GB + Bộ nhớ trong 256GB cho không gian lưu trữ thoải mái. Thêm vào đó, cụm camera cảm biến 200MP cùng camera selfie 20MP cho ảnh chụp, video chi tiết, sắc nét. Không chỉ vậy, màn hình AMOLED DotDisplay độ phân giải FHD+ với tần số quét 120Hz mang đến hình ảnh rực rỡ, sống động.'),
(N'Xiaomi Mi 11 Lite 5G','12','5','240','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/x/i/xiaomi-mi-11-lite-5g-2_10.png',
N'Mi 11 Lite 5G và 4G là bộ đôi vừa được Xiaomi trình làng. So sánh nhanh thì cả hai máy sở hữu cùng kích thước màn hình, thông số cụm camera sau và dung lượng pin. Nhưng bên cạnh đó thì phiên bản 5G vẫn còn một số điểm khác biệt so với bản 4G.'),
(N'Xiaomi Redmi 12C 4GB 64GB','12','5','170','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/f/5/f5677.jpg',
N'Xiaomi Redmi 12C là mẫu điện thoại mới sắp được hãng cho ra mắt thị trường. Mang tới cho người dùng hiệu năng ổn định với con chip MediaTek Helio G85. Cùng với đó là thiết kế ấn tượng, vượt trội. Đặc biệt dung lượng pin siêu khủng tới 5000 mAh cùng sạc nhanh 10W. Đây chắc chắn sẽ là mẫu điện thoại nổi bật nhất trong phân khúc giá rẻ mà bất kỳ ai cũng không thể bỏ qua.'),
(N'Xiaomi Redmi Note 11S','12','5','260','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/r/e/redmi-note-11-s-bl.jpg',
N'Xiaomi Redmi Note 11S sở hữu một thiết kế cuốn hút với các đường nét hoàn thiện tỉ mỉ. Điện thoại sở hữu màn hình kích thước 6.43 inch cùng độ tần số quét 90Hz mang lại các chuyển động ổn định và mượt mà. Bên trong thiết bị sẽ chạy trên con chip MediaTek Helio G96CPU cùng bộ nhớ RAM lên đến 8GB.'),
(N'Xiaomi POCO M5 4GB 64GB','12','5','140','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/f/v/fvssxa.jpg',
N'Mặt trước của Xiaomi POCO M5 là một màn hình 6,58 inch có độ phân giải Full HD+. Nhờ đó mà không có gì quá ngạc nhiên khi POCO M5 lại sở hữu khả năng hiển thị với độ chi tiết cao và màu sắc sống động. Máy cũng có thêm các tính năng khác như Sunlight nhằm hỗ trợ người chơi có thể sử dụng thoải mái ở nhiều điều kiện ánh sáng.'),
(N'Xiaomi Poco F4','12','5','230','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/x/i/xiaomi_poco_f4_negro_01_l.jpg',
N'Xiaomi Poco F4 với thiết kế khác hoàn toàn so với những máy tiền nhiệm trước đây. Với cạnh viền vuông tạo nên sự mạnh mẽ, cá tính, không kém phần sang trọng, tạo sự thú vị khác biệt với nhiều sản phẩm điện thoại cùng phân khúc hiện nay. Camera sắc nét ấn tượng giúp người dùng nắm bắt từng khoảnh khắc nhờ máy ảnh selfie là 20MP, rõ ràng, sinh động. Ngoài ra, sản phẩm với hệ thống có ba camera, gọn gàng, không chiếm diện tích của máy, phía sau còn gồm có cảm biến chính lên đến 64MP. Phóng tầm nhìn với góc rộng là 8MP và kèm theo là camera macro 2MP, tạo cảm giác rõ nét, rộng hơn khi chụp ảnh.'),
(N'Poco X4 GT','12','5','355','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/p/m/pms_1655902438.71275038_1.png',
N'POCO X4 GT được trang bị bộ vi xử lý mạnh mẽ nhất thuộc phân khúc tầm trung đến từ thương hiệu MediaTek Dimensity 8100. Con chip này được sản xuất theo tiến trình 5nm, có 8 nhân. Trong đó 4 nhân hiệu suất với xung nhịp là 2.85 GHz và 4 nhân tiết kiệm với xung nhịp 2.0 GHz.'),
(N'Xiaomi Redmi 10A','12','5','120','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/p/m/pms_1650393946.86423132.png',
N'Xiaomi Redmi 10A sở hữu màn hình giọt nước kích thước 6.53 inches. Ngoài ra, tấm nền IPS LCD trong máy cho khả năng hiển thị hình ảnh gam màu rộng, giảm ánh sáng tán xạ, tái tạo lại màu sắc và đem đến góc nhìn rộng. Thêm vào đó, độ phân giải HD+ (720 x 1640 pixel) mang đến khả năng hiển thị sống động, ổn định. Máy với màn hình kích thước lớn mang lại không gian hiển thị rộng rãi. Nhờ đó người dùng có thể thoải mái sử dụng, lướt web và xem phim.'),
(N'Xiaomi POCO X4 Pro','12','5','270','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/4/0/40_1_21.jpg',
N'Xiaomi POCO X4 Pro được trang bị một màn hình kích thước lớn lên đến 6,67 inch. Màn hình sử dụng tấm nền AMOLED cùng dải màu rộng DCI-P3 mang lại trải nghiệm hình ảnh sắc nét, chi tiết sống động. Màn hình còn được trang bị mặt kính cường lực Gorilla Glass 5 mang lại khả năng bảo vệ màn hình hiệu quả.'),
(N'Redmi A1','12','5','180','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/w/1/w1q1111c_.jpg',
N'Redmi A1 sử dụng con chip Mediatek Helio A22 có cấu trúc 12nm với 4 nhân và xung nhịp 2.0GHz. Kết hợp với đó là 2GB RAM đảm bảo cho smartphone có thể chuyển đổi mượt mà giữa nhiều tác vụ và xử lý chúng một cách nhanh chóng. Máy đi kèm với bộ nhớ trong 32GB, có thể mở rộng với thẻ nhớ microSD đủ đáp ứng nhu cầu lưu trữ thông thường.'),
(N'Galaxy S23 Ultra','7','5','470','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/s/2/s23-ultra-xanh.png',
N'Samsung Galaxy S23 Ultra sử dụng chipset Snapdragon 8 Gen 2 Mobile Platform for Galaxy. Chipset này hứa hẹn mang đến khả năng xử lý mạnh mẽ cân mọi thao tác đặc biệt có thể chạy nền cùng lúc nhiều ứng dụng mà không gây giật lag.'),
(N'Galaxy A34 5G','7','5','240','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/s/m/sm-a346_galaxy_a34_5g_awesome_silver_front.png',
N'Samsung Galaxy A34 được trang bị bộ vi xử lý MT D1080 8 nhân tới từ chính thương hiệu này. Với bộ vi xử lý này, Galaxy A34 sẽ có hiệu năng thuộc hàng tốt nhất trong phân khúc điện thoại tầm trung để đảm bảo thiết bị hoạt động mượt mà. Đi kèm với con chip MT D1080 là 8GB RAM và 128GB bộ nhớ trong để máy có thể thực hiện đa nhiệm một cách dễ dàng cũng như mang tới cho bạn một không gian lưu trữ thoải mái. Galaxy A34 còn có thể mở rộng bộ nhớ thông qua thẻ microSD nếu bạn lo lắng về vấn đề hết dung lượng.'),
(N'Galaxy S23','7','5','370','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/_/g/_global-version_-sm-s911_galaxys23_front_phantomblack_221122.jpg',
N'Samsung Galaxy S23 được trang bị màn hình 6.1 inch kết hợp với đó là khung viền mỏng, thiết kế giọt nước giúp không gian hiển thị được tối ưu hơn. Màn hình có tốc độ làm tươi cực ấn tượng cho mọi thao tác vuốt chạm cũng như phản hồi màn hình vô cùng mượt mà và nhanh chóng. Máy còn sở hữu tấm nền chất lượng cao với độ phân giải lớn cho khả năng hiển thị sắc nét. Đặc biệt, màu đen sâu, màu sắc kết hợp hài hoà, dải màu rộng cùng với đó là công nghệ hiện đại giúp bạn có trải nghiệm giải trí sinh động hơn và cũng đảm bảo đôi mắt được bảo vệ tốt hơn khi sử dụng.'),
(N'Galaxy Z Fold4','7','5','470','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/s/a/samsung_galaxy_z_fold_4-7.jpg',
N'Galaxy Z Fold4 là siêu phẩm Samsung đầu tiên sử dụng hệ điều hành Android 12 L, chạy trên One UI 4.1.1. Ở hệ điều hành này, Z Fold4 đã tối ưu hóa được các ứng dụng chạy trên màn hình gập bằng tác vụ chuyên dụng. Nhờ vậy, việc chuyển đổi giữa các ứng dụng trở nên đơn giản và dễ dàng hơn. Đặc biệt Android 12L cho phép người dùng chuyển đổi cài đặt nhanh và sử dụng 2 cột thông báo. Thêm vào đó, tính năng dạng gấp hỗ trợ chuyển đổi bố cục dựa trên hoạt động mở ra hay gấp lại của điện thoại. Đồng thời, thiết bị còn có khả năng khởi động và chuyển đổi các ứng dụng ở chế độ đa nhiệm song song.'),
(N'Galaxy A54 5G','7','5','120','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/s/m/sm-a546_galaxy_a54_5g_awesome_violet_front.png',
N'Đặc biệt, điểm mới trên Galaxy A54 5G chính là màn hình tràn viền cho trải nghiệm hình ảnh thêm cao cấp. Chiếc máy sử dụng công nghệ màn hình notch đục lỗ để tích hợp camera selfie. Và màn hình của Galaxy A54 5G sẽ có kích thước 6.4 inch với nền màu Super AMOLED độ phân giải FHD+. Ngoài ra tốc độ làm mượt 120 Hz cũng hiện diện trên màn hình Samsung Galaxy A54 5G. Samsung Galaxy A54 5G sẽ thỏa mãn nhu càu chụp ảnh siêu nét của bạn với bộ ba camera sau ấn tượng. Cụ thể, camera chính của Galaxy A54 5G sẽ có độ phân giải 50 MP được tối ưu khả năng chụp đêm và chống rung quang học. Hai camera camera trên Galaxy A54 5G sẽ bao gồm một ống kính chụp siêu rộng 12 MP và ống kính 5 MP với tính năng chụp cận macro và chụp chân dung rõ nét.'),
(N'Galaxy A14 5G','7','5','140','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/6/1/61c76810-d69e-4f77-bfc3-15e1a914a4bb.png',
N'Về camera Samsung Galaxy A14 không chỉ mang đến cho người dùng sự mới mẻ với thiết kế mà độ phân giải của ống kính cũng được nâng cấp một cách vượt bậc lên tới 50MP. Có lẽ đây là ưu ái lớn nhất khi Samsung nâng cấp cho phiên bản mới nhất của mình. Bên cạnh đó phải kể từ những tính năng thông minh. Chúng được kết hợp với các thuật toán xử lý hình ảnh vô cùng chuyên nghiệp đến từ thương hiệu. Tất cả để giúp người dùng có được những bức ảnh vô cùng sắc nét và có độ chi tiết cao.'),
(N'Galaxy S23 Plus','7','5','350','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/_/g/_global_version_sm-s916_galaxys23plus_front_green_221122.jpg',
N'Samsung Galaxy S23 Plus trang bị màn hình 6.6 inch, công nghệ màn hình sắc nét, với cụm camera sau ấn tượng với camera góc siêu rộng 12 MP, camera góc rộng 50MP, ống kính tele 10MP . Bên cạnh đó, với con chipset mạnh mẽ Snapdragon 8 Gen 2, RAM 8GB và phiên bản bộ nhớ trong 256GB/512GB ổn định khi dùng trong thời gian dài. Người dùng sẽ có những khoảnh khắc bên điện thoại cả ngày, chiến game, giải trí với dung lượng pin 4700mAh.'),
(N'Galaxy A23 5G','7','5','170','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/1/_/1_292.jpg',
N'Chiếc điện thoại Samsung Galaxy A23 5G sẽ mang đến cái nhìn tổng thể vô cùng tuyệt vời qua những hình ảnh được tiết lộ. Màn hình Infinity-V IPS LCD kích thước 6.6 inch sẽ được giữ lại. Thêm vào đó là tính năng cuộn siêu mượt, giúp cho người dùng có trải nghiệm lướt hiệu quả hơn. Đồng thời thiết bị còn được hỗ trợ RAM 4GB để giúp tăng hiệu quả làm việc và nhanh chóng hơn. Bộ nhớ trong 64GB cùng sự hỗ trợ của thẻ MicroSD có thể lên đến tối đa 1TB mang đến một không gian lưu trữ rộng lớn và khả năng đa nhiệm mượt mà. Điện thoại cũng được trang bị sự bảo mật an toàn, nhiều lớp, giúp bảo vệ thông tin an toàn và tránh được những đe dọa độc hại.'),
(N'Galaxy A23 4G','7','5','170','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/s/a/samsung-galaxy-a23-cam-thumb-600x600_1.jpg',
N'Samsung A23 (4GB|128GB) là điện thoại phân khúc tầm trung đến từ thương hiệu Samsung sở hữu bộ cấu hình ấn tượng. Trong đó bao gồm con chip Snapdragon 680, màn hình Full HD+ lớn với kích thước 6.6 inch, đi cùng với tần số quét 90Hz. Máy còn nổi bật với viên pin 5000mAh với công suất sạc lớn đến 25W.'),
(N'Galaxy A13 4G','7','5','150','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/g/a/galaxy_a13.jpg',
N'Samsung A13 có màn hình 6.6 inch, với công nghệ TFT LCD, càng tăng cảm giác ấn tượng khi sử dụng, với cụm camera sắc nét, 50 MP với camera sau và camera trước là 8MP, thỏa sức với đam mê chụp ảnh của bản thân. Dung lượng điện thoại là 4GB+ 128Gb, xem phim, lướt web nhiều giờ liền. Dung lượng pin của điện thoại lên đến 5.000 mAh, sử dụng phục vụ nhu cầu cá nhân khác nhau.'),
(N'Galaxy S21 FE','7','5','240','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/s/m/sm-g990_s21fe_backfront_lg.png',
N'Samsung Galaxy S21 FE (8GB - 128GB) được cung cấp sức mạnh bởi con chip xử lý Exynos 2100 "cây nhà lá vườn" kết hợp với 8GB RAM mang đến hiệu suất hoạt động mạnh mẽ cùng bộ nhớ trong 128GB giúp người dùng có thể thoải mái lưu trữ hình ảnh, video dữ liệu.'),
(N'Galaxy Z Fold3 5G','7','5','370','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/s/m/sm-f926_zfold3_5g_openback_phantomgreen_210602.jpg',
N'Galaxy Z Fold3 được trang bị con chip Snapdragon 888 cho xung nhịp xử lý nằm ở mức khá cao. Giúp mọi thao tác mọi ứng dụng đều được xử lý nhanh chóng trên cả 2 màn hình rất hiệu quả và mượt mà. Bộ nhớ ram của máy cũng cho dung lượng lên đến 12GB ngang mới một một chiếc laptop cao cấp. Thế hệ ram là loại DDR5 tối ưu đa nhiệm cực tốt, hầu hết mọi ứng dụng nặng nhất đều có thể sử dụng cùng lúc mượt mà.'),
(N'Galaxy A73 5G','7','5','220','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/a/7/a73-xanh.jpg',
N'Samsung Galaxy A73 có thể hoạt động một cách mượt mà là nhờ vào chip xử lý Snapdragon 778G sản xuất bởi Qualcomm với bộ xử lý tám nhân Octa-core hiện đại. Với một chip xử lý như trên, chiếc điện thoại A73 của bạn có thể đảm nhiệm nhiều tác vụ cùng lúc, từ nhẹ đến nặng một cách thoải mái và trơn tru. Bộ xử lý đồ họa GPU Adreno được trang bị giúp cấu hình thêm mạnh mẽ.'),
(N'Galaxy A54 8GB 256GB','7','5','210','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/s/m/sm-a546_galaxy_a54_5g_awesome_violet_front_2.png',
N'Samsung A54 đột phá với màn hình Super AMOLED 6.4 inch tràn viền vô cực Infinity-O, độ sáng đến 1000nits, tần số quét lên đến 120Hz. Dòng điện thoại này cũng sở hữu cụm 3 camera phân giải cao 50.0 MP + 12.0 MP + 5.0 MP với tính năng ổn định kỹ thuật số và Auto-framing kết hợp chống rung OIS.'),
(N'Galaxy A53 5G','7','5','280','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/_/s/_sm-a536_04._device_design_m_1_2.jpg',
N'Samsung Galaxy A54 ra mắt với màn hình Super AMOLED 6.4 inch tràn viền vô cực Infinity-O, độ sáng đến 1000nits, tần số quét lên đến 120Hz. Kèm với đó là cụm 3 camera phân giải cao 50.0 MP + 12.0 MP + 5.0 MP với tính năng ổn định kỹ thuật số và Auto-framing kết hợp chống rung OIS.'),
(N'Galaxy A52s 5G','7','5','255','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/a/5/a52s-xanhla-01.jpg',
N'Camera trên Samsung Galaxy A52s 5G sẽ mang đến cho người dùng những shoot hình vô cùng độc đáo với các thông số: 64 MP, 12 MP, 5 MP và 5 MP. Bên cạnh thông số ấn tượng là các công nghệ vô cùng hiện đại như: hỗ trợ chống rung quang học OIS cao cấp giúp hình ảnh luôn đảm bảo chất lượng, khả năng lấy nét chính xác ngay cả khi bạn chụp trong điều kiện thiếu sáng.'),
(N'Galaxy A33 5G','7','5','180','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/d/o/download_5__2_1.png',
N'Samsung Galaxy A34 với nhiều cải tiến như màn hình Super AMOLED 6.6 inch, tần số quét 120Hz, độ sáng lên đến 1.000 nits, pin 5.000mAh với camera sắc nét tích hợp công nghệ chống rung OIS. Galaxy A33 cũng được Samsung trang bị chuẩn kháng nước và bụi bẩn IP67, đây là tính năng chỉ được xuất hiện trên các dòng cao cấp như S hoặc Note. Với chuẩn kháng nước chất lượng này, Samsumg A33 có khả chịu được nước trong thời gian 30 phút dưới độ sâu 1m. Tuy nhiên, hãng sản xuất sẽ không bảo hành tính năng này do đó không khuyến khích người dùng test thử tính năng này.'),
(N'Galaxy A04s','7','5','159','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/h/_/h_ng_d_a4.jpg',
N'Samsung A04s (4GB/64GB) là điện thoại mới phân khúc giá rẻ, sở hữu chip 8 nhân Exynos 850, khả năng đa nhiệm, lưu trữ ổn định, chụp ảnh đẹp. Thêm vào đó, màn hình LCD 6.5 inch có độ phân giải HD+ và tần số quét 90Hz cho trải nghiệm hình ảnh sắc nét, rõ ràng.'),
(N'Galaxy M14 5G','7','5','179','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/l/b/lb-galaxy-m14-sm-m146-sm-m146bzbvmea-535834833.png',
N'Samsung Galaxy M14 thu hút được sự chú ý của người dùng với thiết kế vuông vức, thời thượng, trang bị chipset nội bộ của Samsung Exynos 1330. Màn hình hiển thị được cấu thành từ tấm nền IPS LCD thế hệ mới, đem lại những trải nghiệm hình ảnh sắc nét, sống động. Cụm camera với độ phân giải có thể đạt 50MP cùng dung lượng pin lên tới 6000mAh, giúp nâng cao hiệu quả sử dụng của người dùng.'),
(N'Galaxy A14 4G','7','5','249','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/d/g/dgrgt6775.jpg',
N'Samsung Galaxy A14 4G có màn hình rộng 6.6 inch, tần số quét 60Hz, cụm camera 50MP+5MP+2MP và camera selfie 13MP. Dung lượng pin của máy lên đến 5.000 mAh, sử dụng cả ngày dài, khi gần cạn pin nhanh chóng nạp đầy thông qua củ sạc đi kèm. Nhờ vậy, người dùng có thể dễ dàng lướt web, đắm mình trong thế giới giải trí hay tận hưởng khoảnh khắc vui vẻ bên cạnh người thân, gia đình.'),
(N'Galaxy A04','7','5','199','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/8/_/8_76.jpg',
N'Điện thoại Samsung Galaxy A04 thực hiện một nâng cấp lớn đầu tiên đó là công nghệ màu. Điện thoại Galaxy A04 lần này sử dụng công nghệ màn hình LCD cho màu sắc hiển thị tốt hơn và rực rỡ. Ngoài ra, điện thoại Samsung Galaxy A04 cũng giữ nguyên kích thước màn hình 6.5 inch và độ phân giải 1600 x 720 pixels (HD+) cho trải nghiệm quan sát bắt mắt.'),
(N'Galaxy A73','7','5','179','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/s/a/samsung-galaxy-a73-1-600x600_3.jpg',
N'Nếu nhu cầu lưu trữ của bạn cao hơn thì có thể tham khảo ngay Samsung A73 phiên bản 256GB bộ nhớ trong đang được phân phối độc quyền tại hệ thống CellphoneS với mức giá chênh lệch không quá nhiều so với bản 128GB.'),
(N'Nokia C21 Plus','14','5','165','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/n/o/nokia-c21-plus-600x600.jpg',
N'Nokia C21 Plus sở hữu bộ đôi camera sau 13MP+2MP. Trong đó, camera chính của điện thoại Nokia C21 Plus còn hỗ trợ thêm tính năng chụp góc rộng kèm theo tự động lấy nét giúp bạn có thể thỏa sức sáng tạo nên những bức ảnh bắt trọn nhiều khoảnh khắc đáng nhớ. Ngoài ra, camera phụ 2,P hỗ trợ chế độ chụp chân dung tạo nên những bức ảnh nghệ thuật đỉnh cao.'),
(N'Nokia G22','14','5','349','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/d/g/dgtyi8899_.jpg',
N'Nokia G22 thu hút được sự chú ý của người dùng nhờ thiết kế cực kỳ nhỏ gọn, thanh lịch. Dù sở hữu một thông số hiệu năng ổn định - chip Unisoc T606, cùng các tính năng hiện đại khác nhưng G22 lại sở hữu một mức giá cực hấp dẫn, chỉ khoảng 4.5 triệu VND. Màn hình hiển thị HD+ mang lại chất lượng hình ảnh chân thật, sắc nét. Dung lượng Pin mà Nokia G22 sở hữu lên tới 5050 mAh cùng công suất sạc 20W.'),
(N'Nokia C31','14','5','299','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/1/_/1_250_1.jpg',
N'Bộ 3 camera AI sắc nét 13MP tích hợp ứng dụng Camera từ Google cho những bức ảnh hoàn hảo. Màn hình siêu rộng 6.7” chuẩn HD+ mang đến trải nghiệm giải trí chất lượng cao với hình ảnh sống động. Hệ điều hành Android 12 mới nhất với tính năng bảo mật và chia sẻ dễ dàng kết hợp vi xử lý 8 nhân mạnh mẽ giúp thao tác mượt mà và dung lượng pin 5050 mAh, cùng chế độ siêu tiết kiệm pin cho thời gian sử dụng lên đến 3 ngày, tiêu chuẩn kháng nước IP52 phù hợp với điều kiện thời tiết tại Việt Nam. Trọn an tâm với 02 năm cập nhật bảo mật hàng quý, mở khóa vân tay và nhận diện khuôn mặt'),
(N'Asus ROG Phone 6','18','5','255','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/a/s/asus-rog-phone-6-12gb-256gb_2.png',
N'Điện thoại Asus ROG Phone 6 sở hữu màn hình kích thước 6.78 inch cùng tần số quét tới 165Hz, dải màu DCI-P3 lên tới 111%. Cấu hình điện thoại cũng vô cùng ấn tượng với con chip Qualcomm Snapdragon 8+ gen 1 cùng bộ nhớ RAM tới 16GB, bộ nhớ ROM 512GB. Không chỉ tối ưu hóa chơi game, Asus ROG Phone 6 cũng tối ưu hóa trong nhiếp ảnh với cụm ba camera, ống kính chính 50MP, ống kính selfie 12MP.'),
(N'Asus ROG Phone 5','18','5','255','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/a/s/asus-rog-phone-5_0002_gsmarena_001.jpg',
N'Asus ROG Phone tối ưu hóa trải nghiệm quan sát trong từng trò chơi với màn hình 6.78 inch Full HD+ (2400 x 1080 pixels). Sử dụng nền màu AMOLED, với tần số quét đến 144 Hz và chế độ hình ảnh HDR10+ tương phản 100.000:1, bất kỳ tựa game nào, dù là sinh tồn hay phiêu lưu, cũng sẽ trở nên sống động với cài đặt hình ảnh tối đa trên chiếc điện thoại này.'),
(N'Asus ROG Phone 5S','18','5','379','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/h/7/h732_4__1.png',
N'Asus ROG Phone 5S. Bởi lẽ con chip Snapdragon mang tên Qualcomm Snapdragon 888 5G được cho là vi xử lý mạnh mẽ nhất của Snapdragon. Chip được sản xuất trên tiến trình 5 nm, tích hợp cùng với CPU Kryo 680 nhằm giúp tăng hiệu suất của khả năng xử lý dữ liệu lên 25% và đồng thời GPU được tích hợp cho khả năng hiển thị đồ họa cao gấp 35% lần so với thế hệ cũ.'),
(N'Asus ROG Phone 3','18','5','249','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/r/o/rog_3.jpg',
N'Camera sau của ROG Phone 3 ống kính chính là cảm biến Sony 64MP, hai ống kính còn lại là camera góc rộng có độ phân giải 13MP và ống kính 5MP. Với trợ lý đắc lực là đèn Dual-LED flash. Camera này còn hỗ trợ chế độ chụp HDR, panorama, quay video chất lượng 4K. Điện thoại ROG Phone 3 trang bị bộ xử lý Snapdragon 865 Plus mới nhất để tích hợp vào sản phẩm. Kết hợp với RAM 12GB và bộ nhớ trong tốc độ cao 512GB, chiếc máy này đủ khả năng xử lý tất cả các tựa game trên di động hiện nay.'),
(N'Tai nghe Asus ROG Delta Core','18','1','79','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/a/s/asus_rog_delta_core_1.png',
N'Tai nghe gaming Asus Rog Delta Core được cập nhật công nghệ lọc tín hiệu âm thanh hiện đại nhất hiện nay. Từ đó giúp cho màng loa hỗ trợ tách âm thanh tần số cao, thấp và vừa, đồng thời giảm độ nhiễu giữa các dải tần để mang đến âm thanh trong hơn và rõ nét hơn. Tai nghe gaming Asus Rog Delta Core được cập nhật công nghệ lọc tín hiệu âm thanh hiện đại nhất hiện nay. Từ đó giúp cho màng loa hỗ trợ tách âm thanh tần số cao, thấp và vừa, đồng thời giảm độ nhiễu giữa các dải tần để mang đến âm thanh trong hơn và rõ nét hơn.'),
(N'Tai nghe ROG Theta 7.1','18','1','139','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/t/a/tai-nghe-gaming-asus-rog-theta-7-1-1.jpg',
N'Tai nghe chụp tai ASUS ROG Theta có đến 4 driver ASUS Essence nhằm hỗ trợ công nghệ subwoofer ảo mang đến dải âm trường rộng, âm bass sâu. Từ đó, trải nghiệm nghe của người dùng cũng rõ ràng và đã hơn. ASUS ROG Theta 7.1 được thiết kế đi kèm bộ DAC 7.1 với bộ giải mã âm thanh SupremeFX S1220A. Bên trong DAC cung cấp 4 bộ khuếch đại tai nghe ESS 9601 giúp mang đến hiệu ứng chính xác hơn trong phạm vi âm thanh khuếch tán rộng.'),
(N'Tai nghe Asus TUF H3','18','1','99','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/t/a/tai-nghe-gaming-asus-tuf-h3-3.jpg',
N'Tai nghe chụp tai Gaming Asus TUF H3 được trang bị màng loa lớn gấp nhiều lần so với một chiếc loa thông thường, là 50mm, giúp mang đến công nghệ âm thanh lên mức cực đại, đã tai vô cùng. Bên cạnh đó, tai nghe còn được tích hợp thêm âm thanh vòm 7.1 để mang đến chất âm sâu lắng và rõ nét. Điều đó, nó giúp bạn có cảm giác chân thật khi bước đến vào cổng thế giới trò chơi.'),
(N'Tai nghe Asus TUF H1','18','1','49','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/2/6/26_1_90.jpg',
N'Tai nghe chụp tai Gaming ASUS TUF H1 được trang bị micro đạt chuẩn chất lượng giao tiếp rõ ràng từ Discord và TeamSpeak. Do đó, khi nói chuyện thì giọng của bạn sẽ được tinh chỉnh giúp người nghe bên kia tiếp nhận nhanh chóng và chính xác. Vì tích hợp mic nên để đảm bảo người sử dụng cảm thấy thoải mái thì tai nghe Gaming ASUS TUF H1 đã trang bị khung tai nghe có dây bằng vải mang lại sự linh hoạt và giảm tình trạng đau ở đỉnh sau khi sử dụng trong thời gian dài.'),
(N'Tai nghe Asus ROG Strix Fusion 500','18','1','249','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/a/s/asus_rog_strix_fusion_500_2.png',
N'Tai nghe chụp tai Asus ROG Strix Fusion 500 sở hữu thiết kế chắc chắn với toàn thân được phủ nhựa cao cấp, mang đến độ bền cao giúp chống chọi với mọi loại tác động thông thường. Điểm đặc biệt nằm ở bộ phận housing được thiết kế độc đáo được lấy từ hình tượng của những tựa game thông dụng, chỉ cần đeo vào là đã có tinh thần chiến game. Tai nghe chụp tai Asus ROG Strix Fusion 500 sở hữu thiết kế chắc chắn với toàn thân được phủ nhựa cao cấp, mang đến độ bền cao giúp chống chọi với mọi loại tác động thông thường. Điểm đặc biệt nằm ở bộ phận housing được thiết kế độc đáo được lấy từ hình tượng của những tựa game thông dụng, chỉ cần đeo vào là đã có tinh thần chiến game.'),
(N'Tai nghe chụp tai Nokia HP-101','14','1','149','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/_/0/_0004_hp-101_bk_a03.jpg',
N'Tai nghe Nokia HP-101 này còn được nhà Nokia trang bị thêm cho phần mềm driver có âm thanh và kích thước cực lớn có thể cho đến 40mm cùng đó là tần số đạt 20Hz - 20kHz giúp mang lại được cho người dùng có được những trải nghiệm âm thanh sống động, chân thực và phong phú.'),
(N'Tai nghe Sony WH-1000XM5','4','1','259','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/t/a/tai-nghe-chup-tai-sony-wh-1000xm5-2-removebg-preview.png',
N'Tai nghe sở hữu thiết kế kiểu choàng đầu phong cách cá tính. Khi không sử dụng, bạn có thể gấp gọn lại và thuận tiện cho bạn mang theo trong công việc hay bất cứ nơi đâu. Đặc biệt, bao bì tai nghe không sử dụng nhựa thay vào đó là các vật liệu tái chế an toàn cho môi trường. Tai nghe sở hữu thiết kế kiểu choàng đầu phong cách cá tính. Khi không sử dụng, bạn có thể gấp gọn lại và thuận tiện cho bạn mang theo trong công việc hay bất cứ nơi đâu. Đặc biệt, bao bì tai nghe không sử dụng nhựa thay vào đó là các vật liệu tái chế an toàn cho môi trường.'),
(N'Tai nghe Sony WH-CH720N','4','1','259','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/w/h/wh-ch720_blue01_m.png',
N'Tai nghe Sony WH-CH720N được thiết kế theo dạng Over-ear hiện đại. Do được hoàn thiện từ chất liệu Composite sợi Carbon cao cấp, CH720N có độ bền bỉ và vô cùng chắc chắn trong quá trình sử dụng. Đồng thời, ưu điểm này cũng giúp phân khúc tai nghe mới này có trọng lượng khá nhẹ. Do đó, nó được quảng cáo là chiếc tai nghe chụp chống ồn chủ động nhẹ nhất hiện nay. Phần đệm tai và đầu của Sony WH-CH720N cũng khá êm ái. Tạo cảm giác nhẹ nhàng, thăng hoa trong từng giai điệu.'),
(N'Tai nghe Sony WH-CH510','4','1','149','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/t/a/tai_nghe_kho_ng_da_y_wh-ch510_7_1.png',
N'Sony vừa mới cho ra mắt chiếc tai nghe bluetooth Sony WH-CH510 có thiết kế gọn nhẹ và dễ dàng gập bẻ. Ngoài ra, điểm đặc biệt của chiếc tai nghe chùm đầu không dây Sony WH-CH510 là chúng có thời lượng pin nghe rất dài lên đến 35 giờ. Mang trong mình thiết kế vỏ ngoài gọn nhẹ với trọng lượng chỉ 132 g, cùng với đó là việc Sony WH-CH510 có khả năng gập mở linh hoạt, linh hoạt. Nhờ vậy tai nghe có thể dễ dàng mang theo bên mình trong những chuyến đi xa mà không ngại đến khả năng chiếm dụng không gian của chiếc tai nghe không dây này.'),
(N'Tai nghe Sony MDR-ZX110AP','4','1','289','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/t/r/tr_ng-1_9_1_.jpg',
N'Tai nghe Sony MDR-ZX110AP là một trong những sản phẩm giá rẻ nổi bật của Sony một tập đoàn đa quốc gia, đa ngành nghề có lịch sử lâu đời. Sản phẩm phụ kiện âm thanh của hãng đi vào tiềm thức người dùng và để lại nhiều ấn tượng về thiết kế, chất lượng cũng như độ bền. Tai nghe Sony MDR-ZX110AP là một trong những sản phẩm giá rẻ nổi bật của Sony một tập đoàn đa quốc gia, đa ngành nghề có lịch sử lâu đời. Sản phẩm phụ kiện âm thanh của hãng đi vào tiềm thức người dùng và để lại nhiều ấn tượng về thiết kế, chất lượng cũng như độ bền.'),
(N'Tai nghe gaming Sony Inzone H7','4','1','429','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/1/0/10_9_107.jpg',
N'Những chiếc tai nghe Sony Inzone H7 có ngoại hình tinh tế với phần đệm đầu rộng làm từ chất liệu mềm mại có thể phân bố trọng lực đều đến mọi điểm tiếp giáp. Điều này tạo nên cảm giác thoải mái và dễ chịu dù bạn đã đeo tai nghe suốt thời gian dài liên tục. Miếng đệm tai mềm được tạo nên từ Nylon nhẵn mịn ôm sát tai hoàn hảo mà không hề gây áp lực nên vùng cánh tai nhạy cảm này. Nhờ vào sự tối ưu hóa điểm tiếp xúc ở đệm tai với hai bên đầu mà ​​Tai nghe Inzone H7 tạo ra cảm giác thoải mái cho tai, không gây bí, nóng khi sử dụng. Hơn hết thiết kế ôm khít tai này giúp tạo ra môi trường cách âm và nâng cao độ ổn định cho tai nghe.'),
(N'Loa tháp Samsung MX-T70','7','2','559','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/d/o/download_1__4_1_1.png',
N'Bạn có thể điều khiển loa tháp MX-T70 một cách chuyên nghiệp với ứng dụng Sound Tower. Kiểm soát và điều chỉnh dễ dàng mọi hiệu ứng về âm thanh và ánh sáng. Trang bị hệ thống ánh sáng DJ vô cùng sôi động, đa dạng tương thích với từng giai điệu. Bạn có thể đắm mình trong không gian của bữa tiệc ánh sáng đa sắc màu cùng âm thanh sôi động. Loa tháp Samsung MX-T70 là thiết bị rất nên trang bị để tận hưởng những buổi tiệc liên hoan thêm trọn vẹn. Hãy mua loa tại cửa hàng CellphoneS, chúng tôi đang có chương trình khuyến mãi giá cho sản phẩm này. Bạn sẽ được chăm sóc bởi những nhân viên chuyên nghiệp và nhận chế độ bảo hành loa theo đúng quy định.'),
(N'Loa thanh Samsung HW-Q600B','7','2','329','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/t/_/t_i_xu_ng_-_2023-01-25t222835.183.png',
N'Loa thanh Soundbar Samsung HW-Q600B sở hữu công nghệ Dolby Atmos/ DTS:X tạo ra chiều sâu âm thanh cực kỳ ấn tượng. Đặc biệt, sản phẩm đem lại trải nghiệm giải trí đỉnh cao với 2 loa trần, kết hợp công nghệ Samsung Acoustic Beam. Hệ thống của dòng loa này khá linh hoạt, khi sử dụng với dòng TV QLED tạo ra 3.1.2 kênh loa. Chưa hết, thiết bị còn tích hợp công nghệ Adaptive Sound, phân tích tín hiệu của âm thanh, để nghe rõ những đoạn hội thoại giữa những nhân vật trong phim.'),
(N'Loa Samsung MX-ST90B/XV','7','2','879','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/_/0/_0003_mx-st50b_007_l-perspective2_black.jpg',
N'Loa tháp Samsung sound tower MX-ST90B được trang bị tính năng Bass Booster, điều này có nghĩa khả năng khuếch đại âm trầm cùng tổng công suất cực đại cho không gian bùng nổ, sôi động hơn. Ngoài ra, sự kết hợp giữa loa Tweeter, loa mid và loa trầm tích hợp trong hệ thống âm thanh mang đến âm điệu to lớn mãnh liệt, bao trùm cả không gian rộng lớn trên loa ST90B. Có thể nói đây là một sản phẩm loa không thể thiếu trong các buổi tiệc tùng đặc biệt. Loa tháp Samsung MX-ST90B chính hãng sẽ mang đến không gian âm nhạc ấn tượng và chất nhạc bùng cháy.'),
(N'Loa thanh Samsung Q-SOUNDBAR Q700B/XV','7','2','629','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/2/0/20_2_51.jpg',
N'Loa Samsung Q-Soundbar Q700B/XV được khoác lên mình bộ màu đen quyến rũ và quyền lực, kết hợp được mọi không gian ngoài trời hay trong nhà. Phù hợp với những nơi có thiết kế cổ điển cho đến hiện đại. Ngoài ra còn có lớp vỏ cứng cáp chắc chắn được làm từ nhựa và kim loại. Loa cũng dễ dàng tháo lắp để vệ sinh bám bẩn. Loa Samsung Q-Soundbar Q700B/XV được khoác lên mình bộ màu đen quyến rũ và quyền lực, kết hợp được mọi không gian ngoài trời hay trong nhà. Phù hợp với những nơi có thiết kế cổ điển cho đến hiện đại. Ngoài ra còn có lớp vỏ cứng cáp chắc chắn được làm từ nhựa và kim loại. Loa cũng dễ dàng tháo lắp để vệ sinh bám bẩn.'),
(N'Loa Sony SRS-X200','4','2','229','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/_/0/_0000_srs-xe200_1_.jpg',
N'Bộ khuếch tán đường thẳng của Sony SRS-XE200 giúp phân phối và truyền âm thanh đi xa hơn trên phạm vi rộng mà không bị ảnh hưởng đến chất lượng. Thiết kế này được lấy cảm hứng từ các buổi hòa nhạc lớn cho không gian tràn ngập các giai điệu. Như vậy, bạn sẽ cảm nhận được cùng một chất lượng âm thanh kể cả ở phía trước hay bên cạnh loa. Sản phẩm sở hữu thiết kế nhỏ gọn, có thêm dây đeo giúp cho việc mang theo bên người càng thêm dễ dàng. Với trọng lượng chưa đến 1kg nên loa Sony SRS-XE200 rất tiện cho việc mang đến các bữa tiệc hoặc các chuyến đi phượt. Vỏ loa Sony được làm bằng chất liệu rất bền bỉ, có thể đặt đứng hoặc nằm tùy theo người dùng.'),
(N'Loa Sony SRS-XB13','4','2','119','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/l/o/loa-bluetooth-sony-srs-xb13-6.jpg',
N'Sony Srs-Xb13 Extra Bass được thiết kế với vỏ ngoài bền bỉ, sẵn sàng cho mọi hoạt động. Thời lượng pin của loa có thể lên đến 16 giờ, một thời gian mà không ai nghỉ chỉ một chiếc loa nhỏ bé có thể có được. Trong suốt quá trình hoạt động, máy sẽ báo chỉ số pin trực tiếp về thiết bị điện thoại của bạn, bạn sẽ dễ dàng theo dõi thời lượng pin hơn bao giờ hết. Sony SRS-XB13 cho phép bạn kết nối Bluetooth dễ dàng và nhanh chóng hơn trên thiết bị thông minh chỉ bằng một lần nhấn. Micro tích hợp giúp bạn thực hiện cuộc gọi rảnh tay dù đang ở nhà hay ra ngoài.'),
(N'Loa Sony SRS-XG300','4','2','229','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/s/o/sony_srs-xg300_5.png',
N'Chiếc loa đi kèm với phần tay cầm linh động bên trên có thể bật lên hoặc rút xuống giúp bạn mang thiết bị đến bất cứ đâu. Ngoài tính linh động cao, dòng loa còn hỗ trợ chỉ số kháng bụi, nước lên đến IP67. Dù mang đến bãi biển hay sử dụng Sony SRS-XG300 để phát nhạc ngoài trời, bạn cũng không phải lo lắng về việc thiết bị sẽ hư hỏng. Sony SRS-XG300 với loa woofer mang lại âm thanh mạnh mẽ trong các bữa tiệc. Bên cạnh đó  loa tweeter phía trước kết hợp cùng bộ tản âm thụ động nhờ đó mang lại âm cao sắc nét, âm trầm mạnh mẽ.'),
(N'Loa Huawei Sound Joy','2','2','219','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/2/_/2_69_32.jpg',
N'Thiết kế Huawei Sound Joy theo dạng hình trụ quen thuộc, có thể đặt sản phẩm theo chiều dọc hoặc chiều ngang ở bề mặt phẳng cũng đều phát ra âm thanh một cách toàn diện. Kích thước thiết bị rất nhỏ gọn, với chiều cao hơn 20cm, chiều rộng 7cm. Bên cạnh đó, trọng lượng cũng chỉ 680g, giúp bạn dễ dàng đem theo đến bất kỳ nơi đâu, mà không bị tốn nhiều diện tích. Sản phẩm Huawei Sound Joy hỗ trợ phát công suất khá lớn, mang đến nguồn âm thanh mạnh mẽ. Đặc biệt, sản phẩm sở hữu công nghệ Devialet Speaker Active Matching để phát ra chất âm trung thực hơn.'),
(N'Laptop Huawei Matebook 14','2','4','439','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/_/0/_0004_huaweimatebook14-2021__1__01.jpg',
N'Khác với những dòng sản phẩm cùng phân khúc khác, Matebook 14 AMD có thiết kế các cạnh xung quanh màn hình với độ dày chỉ 4,9 mm, mang đến tỷ lệ hiển thị hình ảnh so với thân máy là 90%. Một điểm đáng chú ý khác của chiếc laptop cho dân văn phòng này đó là độ phân giải của thiết bị đạt đến 2K (2160 x 1440 pixel), mang đến khả năng hiển thị sắc nét, sinh động trên từng khung ảnh. Laptop Huawei Matebook 14 AMD được trang bị bộ vi xử lý R5-5500U, RAM 16GB và bộ nhớ SSD 512GB. Ngoài ra với những tác vụ nặng, bạn có thể tăng hiệu năng của máy bằng cách nhấn phím tắt Fn+P để chuyển sang chế độ hiệu suất.'),
(N'Laptop Huawei Matebook D16','2','4','249','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/4/_/4_98_1.png',
N'Huawei MateBook D16 sở hữu kích thước màn hình khá rộng, lên tới 16 inch đáp ứng cho việc giải trí, xem phim cực kỳ thỏa mãn. Bên cạnh đó, độ phân giải 1.920 x 1.200 pixel hiển thị sắc nét, chi tiết, nhìn rõ ràng những nội dung trên màn hình. Sản phẩm MateBook D16 có độ sáng tới 300 nits, sử dụng thoải mái ở ngoài trời mà không lo lắng bị lóa. Đặc biệt, màn hình của máy đạt được 100% gam màu sRGB và tỷ lệ tương phản 1200:1, giúp những bạn làm đồ họa, chỉnh sửa hình ảnh, edit video hiệu quả hơn.'),
(N'iphone 14 Pro Max','3','5','469','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/t/_/t_m_20.png',
N'iPhone 14 Pro Max có sự cải thiện lớn màn hình so với iPhone 13 Pro Max. Sự khác biệt giữ phiên bản iPhone 14 Pro Max 256GB và bản tiêu chuẩn 128GB chỉ là bộ nhớ trong. Ngoài ra, iPhone 14 Pro Max có tính năng màn hình luôn bật hoạt động (Always-on Display) với tiện ích màn hình khóa mới trên iOS 16. Người dùng có thể xem các thông tin như lời nhắc, sự kiện lịch và thời tiết mà không cần bật máy lên để xem. Thậm chí, có một trạng thái ngủ cho hình nền, trạng thái này sẽ làm tối hình nền để sử dụng ít pin hơn.'),
(N'Đồng hồ thông minh Huawei Watch GT3 Pro','2','10','379','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/m/k/mkt_odin_product_lmage_fluoroelastomer_front_30_left_en_hq_png_800x800_20220403.png',
N'Chiếc Huawei Watch GT3 Pro có mặt kính cong 3D bắt sáng và tạo ấn tượng với người dùng. Thiết kế đồng hồ Huawei với vỏ ngoài theo phong cách thanh lịch, cổ điển, có độ bóng cao kết hợp vòng tay tinh xảo. Cạnh bên là núm vặn siêu nhạy mang lại khả năng điều khiển tiện lợi. Núm vặn giúp cuộn menu, phóng to thu nhỏ chế độ xem cũng như hỗ trợ điều chỉnh âm lượng.'),
(N'Đồng hồ thông minh Xiaomi Redmi Watch 2 Lite','12','10','119','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/_/0/_0002_xiaomi-redmi-watch-2-lite-black.jpg',
N'Thiết kế của Xiaomi Redmi Watch 2 Lite không có nhiều sự khác biệt so với thế hệ cũ. Phải chăng đây đã là thiết kế hoàn thiện mà một nhà sản xuất đồng hồ thông minh có thể đạt được. Hơn nữa, kích thước của mặt đồng hồ sẽ là 41mm, mang đến cảm giác rất đầm tay và thoải mái đeo trong hàng giờ liền. Ngoài các tính năng thường thấy trên một chiếc đồng hồ thông minh, Xiaomi Redmi Watch 2 Lite còn được hỗ trợ thêm bởi 100 chế độ thể thao được tích hợp sẵn, tiện cho việc tập luyện trở nên hiệu quả hơn.'),
(N'Sạc dự phòng Xiaomi Redmi','12','9','56','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/e/3/e3e503071fe06b5800fc264f95fddbca-removebg-preview_1.jpg',
N'pin sạc dự phòng Xiaomi Redmi 20000mAh sạc nhanh 18W là một lựa chọn hợp lý và hấp dẫn. Thiết bị sở hữu kích thước tổng thể 154 x 73.6 x 27.3mm, có thể thấy mặc dù không nhỏ gọn như nhiều sản phẩm cao cấp khác, nhưng nó chứa dung lượng pin lên đến 20000mAh. Sạc dự phòng Xiaomi này hoàn toàn có thể nằm gọn bên trong balo hay túi xách để người dùng có thể mang đến khắp nơi. Với hiệu suất chuyển đổi cao, pin sạc dự phòng Xiaomi Redmi 20000mAh sạc nhanh 18W có thể sạc 4,3 lần cho Xiaomi Mi A1; 7,1 lần cho iPhone 7; 2,5 lần cho iPad Mini. Đồng thời, pin sạc này cũng có thể sạc cho nhiều loại điện thoại, máy tính bảng khác nhau, thậm chí là smartwatch.'),
(N'Sạc dự phòng Samsung EB P5300x','7','9','89','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/p/i/pin-sac-du-phong-samsung-eb-p5300x-20000mah-25w-2.jpg',
N'Pin dự phòng Samsung EB P5300x 20000mAh 25W đến từ thương hiệu nổi bật trên thị trường hiện nay chính là Samsung. Sở hữu thiết kế được hoàn thiện từ chất liệu cao cấp cho cảm giác cầm nắm cực kì chắc nay. Pin sạc dự phòng Samsung EB P5300x 20000mAh 25W sở hữu dung lượng lên tới 20000mAh cho bạn có thể sạc pin thiết bị của mình nhiều lần. Ngoài ra công suất sạc lên tới 25W nhanh chóng sạc đầy thiết bị với thời gian được rút ngắn. Bộ sạc dự phòng này có kích thước nhỏ và trọng lượng chỉ 392g, với kích thước nhỏ gọn như vậy bạn có thể dễ dàng mang theo để sử dụng bất cứ đâu. Được trang bị đến 1x USB và 2x USB-C cho người dùng có thể sạc nhiều thiết bị cùng lúc.'),
(N'Sạc dự phòng Apple Magsafe MJWY3','3','9','229','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/a/p/apple_magsafe_mjwy3_4.png',
N'Thiết kế của pin dự phòng Apple MagSafe cực kỳ nhỏ gọn, cụ thể chỉ bằng một nửa so với chiếc iPhone 12 Mini, giúp người dùng dễ dàng mang theo phụ kiện đi kèm với điện thoại. Nhờ vào nam châm được căn chỉnh hoàn hảo giữ cho thiết bị gắn vào iPhone 12 hay iPhone chắc chắn hơn. Apple MagSafe có thể sạc cho iPhone với công suất 5W ở chế độ sạc không dây và lên đến 15W khi sử dụng sạc dây.'),
(N'Sạc dự phòng Samsung EB-P3400X','7','9','64','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/s/a/samsung_eb-p3400x_5.png',
N'Pin sạc dự phòng Samsung EB-P34000X có dung lượng 10.000 mAh là lựa chọn tối ưu để cung cấp năng lượng linh hoạt cho các thiết bị thông minh di động. Nếu bạn đang tìm kiếm một thiết kế có độ bền tốt, bảo vệ an toàn cho người dùng và hiệu suất sạc cao thì đây là gợi ý không tồi. Hãy xem đoạn mô tả sau đây để hiểu rõ hơn về thế mạnh khi chọn sạc dự phòng Samsung này. Pin Samsung EB-P34000X có công suất sạc nhanh lên đến 25W, giúp nạp năng lượng nhanh chóng ngay lập tức. Bạn có thể tận hưởng sự tiện ích mọi nơi kể cả khi đang di chuyển trong ngày.'),
(N'Máy ảnh kỹ thuật số Sony ZV-E10L','4','3','449','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/m/a/may-anh-sony-zv-e10_1_1.png',
N'KHÔNG GIAN MÀU SẮC Chuẩn sRGB (với gam màu sYCC) và chuẩn RGB Adobe tương thích với công nghệ tái tạo màu TRILUMINOS Color. CHỨC NĂNG DẢI TẦN NHẠY SÁNG Tắt, Tối ưu hóa dải tần động, Dải tần nhạy sáng cao tự động. PHONG CÁCH SÁNG TẠO Chuẩn, Sống động, Chân dung, Phong cảnh, Hoàng hôn, Đen trắng, Nâu đỏ. CẤU HÌNH ẢNH Có (Tắt / PP1-PP10) Tham số: Mức độ tối, Hệ số ảnh (Phim, Ảnh tĩnh, Cine1-4, ITU709, ITU709 [800%], S-Log2, S-Log3, HLG, HLG1-3), Hệ số ảnh đen, Độ cong, Chế độ màu, Bão hòa, Pha màu, Độ sâu màu, Chi tiết, Sao chép, Thiết lập lại. HIỆU ỨNG ẢNH 13 loại: Máy ảnh đồ chơi (Thường/Mát/Ấm/Xanh lá/Đỏ cánh sen), Màu nổi, Màu đồng chất (Màu, Đen/Trắng), Ảnh cổ điển, Ánh sáng dịu, Phân màu (R/G/B/Y), Đơn sắc tương phản cao, Đơn sắc nhiều tông màu, Lấy nét mềm, Tranh HDR, Thu nhỏ, Màu nước, Minh họa'),
(N'Galaxy Tab S8 WIFI','7','11','239','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/t/a/tab_s8_2.jpg',
N'Mẫu máy tính bảng Samsung Galaxy Tab S8 Wifi với màn hình kích thước lớn 11 inches giúp người dùng có những trải nghiệm hình ảnh rõ nét. Bên cạnh đó, tablet được trang bị con chip Snapdragon 8 Gen 1 siêu mạnh cùng cụm camera 13MP + 6MP thỏa sức sáng tạo. Samsung Galaxy Tab S8 wifi có thiết kế hiện đại, với khung hình rộng 11 inch, người dùng có thể thỏa mãn với cảm giác chơi game, xem phim với viền mỏng nhẹ nhẹ, mặt kính bóng loáng, các nút bấm hoàn thiện tỉ mỉ từng chi tiết nhỏ. Trọng lượng của máy tính bảng vừa phải, không quá cồng kềnh khi di chuyển các vị trí khác nhau.'),
(N'iPad Pro 11','3','11','359','https://cdn2.cellphones.com.vn/x358,webp,q100/media/catalog/product/i/p/ipad-pro-13-select-wifi-spacegray-202210-02.jpg',
N'iPad Pro 11 inch 2022 M2 Wifi 128GB - Nâng cấp lớn hơn, trải nghiệm hiện đại hơn. Sự thay đổi lớn về thiết kế và cấu hình chính là những yếu tố giúp cho iPad Pro 2022 chiếc máy tính bảng mới nhất từ Apple - hứa hẹn sẽ là một trong những mẫu máy tính bảng cực kỳ hấp dẫn trong năm 2022. Nâng cấp kế tiếp xuất hiện trên iPad Pro thế hệ mới chính là hệ thống camera - và cũng là nâng cấp đáng chú ý không kém nếu bạn yêu thích điện ảnh. iPad Pro M2 (2022) sẽ trang bị hệ thống camera: camera chính 12 MP, camera góc siêu rộng 10 MP với khả năng chụp góc siêu rộng và cảm biến LiDAR; cùng với đèn flash kép phục vụ chụp ảnh đêm. Tính năng như HDR vẫn hiện diện trên chiếc iPad Pro mới này.')
go
insert into tb_CT_SANPHAM(IdSP,SoLuongSP,IdMau)
values
(1, 100, 13),
(2, 100, 14),
(3, 100, 12),
(4, 100, 5),
(5, 100, 4),
(6, 100, 1),
(7, 100, 6),
(8, 100, 9),
(9, 100, 8),
(10, 100, 3),
(11, 100, 12),
(12, 100, 10),
(13, 100, 6),
(14, 100, 7),
(15, 100, 8),
(16, 100, 15),
(17, 100, 2),
(18, 100, 5),
(19, 100, 9),
(20, 100, 6),
(21, 100, 14),
(22, 100, 8),
(23, 100, 5),
(24, 100, 10),
(25, 100, 14),
(26, 100, 13),
(27, 100, 9),
(28, 100, 7),
(29, 100, 4),
(30, 100, 13),
(31, 100, 5),
(32, 100, 9),
(33, 100, 2),
(34, 100, 9),
(35, 100, 14),
(36, 100, 10),
(37, 100, 11),
(38, 100, 1),
(39, 100, 13),
(40, 100, 6),
(41, 100, 2),
(42, 100, 13),
(43, 100, 3),
(44, 100, 8),
(45, 100, 14),
(46, 100, 12),
(47, 100, 6),
(48, 100, 8),
(49, 100, 5),
(50, 100, 2),
(51, 100, 1),
(52, 100, 11),
(53, 100, 4),
(54, 100, 9),
(55, 100, 11),
(56, 100, 8),
(57, 100, 10),
(58, 100, 14),
(59, 100, 3),
(60, 100, 6),
(61, 100, 13),
(62, 100, 11),
(63, 100, 3),
(64, 100, 5),
(65, 100, 4),
(66, 100, 2),
(67, 100, 14),
(68, 100, 7),
(69, 100, 1),
(70, 100, 10),
(71, 100, 6),
(72, 100, 9),
(73, 100, 1),
(74, 100, 5),
(75, 100, 10),
(76, 100, 13),
(77, 100, 14),
(78, 100, 7),
(79, 100, 12),
(80, 100, 15),
(81, 100, 5),
(82, 100, 7),
(83, 100, 4),
(84, 100, 6),
(85, 100, 11),
(86, 100, 8),
(87, 100, 1),
(88, 100, 13),
(89, 100, 14),
(90, 100, 10),
(91, 100, 12),
(92, 100, 6),
(93, 100, 9),
(94, 100, 2),
(95, 100, 4),
(96, 100, 5),
(97, 100, 8),
(98, 100, 3),
(99, 100, 7),
(100, 100, 13),
(101, 100, 14),
(102, 100, 10),
(103, 100, 9),
(104, 100, 11),
(105, 100, 8),
(106, 100, 5),
(107, 100, 2),
(108, 100, 4),
(109, 100, 6),
(110, 100, 14),
(111, 100, 12),
(112, 100, 1),
(113, 100, 15),
(114, 100, 7),
(115, 100, 11),
(116, 100, 13),
(117, 100, 10),
(118, 100, 8),
(119, 100, 5),
(120, 100, 9),
(121, 100, 2)
go
Update tb_SANPHAM set NgayNhap = CURRENT_TIMESTAMP where NgayNhap is null

insert into tb_Banner(NgayHH,ImagePathDetail)
values ('2023-06-30 11:09:26.040','https://firebasestorage.googleapis.com/v0/b/ecmmobileshop.appspot.com/o/Banner%2Fbanner_product.png?alt=media&token=08b8cfe5-a3ea-49d5-81d3-66577acbdab9')

insert into tb_BannerSP(IdSP,NgayHH,ImagePathDetail)
values (25,'2023-06-30 11:09:26.040','https://firebasestorage.googleapis.com/v0/b/ecmmobileshop.appspot.com/o/BannerSP%2Fbanner_2_product.png?alt=media&token=e44d22ad-36e6-4a9c-92e9-39fdbad820ee')

insert into tb_DISCOUNTSP(IdSP,GiaTri,NgayHH)
values (5,10,'2023-06-30 11:09:26.040')

