//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcmMobileShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcmMobileShopEntities : DbContext
    {
        public EcmMobileShopEntities()
            : base("name=EcmMobileShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Banner> tb_Banner { get; set; }
        public virtual DbSet<tb_BannerSP> tb_BannerSP { get; set; }
        public virtual DbSet<tb_CHITIETHOADON> tb_CHITIETHOADON { get; set; }
        public virtual DbSet<tb_CT_SANPHAM> tb_CT_SANPHAM { get; set; }
        public virtual DbSet<tb_DISCOUNTKH> tb_DISCOUNTKH { get; set; }
        public virtual DbSet<tb_DISCOUNTSP> tb_DISCOUNTSP { get; set; }
        public virtual DbSet<tb_DISCOUNTTIME> tb_DISCOUNTTIME { get; set; }
        public virtual DbSet<tb_FEEDBACK> tb_FEEDBACK { get; set; }
        public virtual DbSet<tb_HANGSP> tb_HANGSP { get; set; }
        public virtual DbSet<tb_HOADON> tb_HOADON { get; set; }
        public virtual DbSet<tb_KHACHHANG> tb_KHACHHANG { get; set; }
        public virtual DbSet<tb_LOAISP> tb_LOAISP { get; set; }
        public virtual DbSet<tb_MAUSAC> tb_MAUSAC { get; set; }
        public virtual DbSet<tb_SANPHAM> tb_SANPHAM { get; set; }
        public virtual DbSet<tb_TINHTRANGDH> tb_TINHTRANGDH { get; set; }
        public virtual DbSet<tb_YKIEN> tb_YKIEN { get; set; }

        public System.Data.Entity.DbSet<EcmMobileShop.Models.SignUpModel> SignUpModels { get; set; }
    }
}
