//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcmMobileShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CHITIETHOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_CHITIETHOADON()
        {
            this.tb_FEEDBACK = new HashSet<tb_FEEDBACK>();
        }
    
        public int IdctHD { get; set; }
        public Nullable<int> IdHD { get; set; }
        public Nullable<int> IdctSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<double> SoLuongBan { get; set; }
        public Nullable<double> GiaBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_FEEDBACK> tb_FEEDBACK { get; set; }
        public virtual tb_CT_SANPHAM tb_CT_SANPHAM { get; set; }
        public virtual tb_HOADON tb_HOADON { get; set; }
    }
}
