//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcmMobileShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CT_SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_CT_SANPHAM()
        {
            this.tb_CHITIETHOADON = new HashSet<tb_CHITIETHOADON>();
        }
    
        public int IdctSP { get; set; }
        public Nullable<int> IdSP { get; set; }
        public Nullable<int> SoLuongSP { get; set; }
        public int IdMau { get; set; }
        public string ImagePathDetail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CHITIETHOADON> tb_CHITIETHOADON { get; set; }
        public virtual tb_MAUSAC tb_MAUSAC { get; set; }
        public virtual tb_SANPHAM tb_SANPHAM { get; set; }
    }
}
