//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcmMobileShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_FEEDBACK
    {
        public int IdFB { get; set; }
        public int IdctHD { get; set; }
        public string Noidung { get; set; }
        public string Img { get; set; }
        public Nullable<System.DateTime> NgayFB { get; set; }
    
        public virtual tb_CHITIETHOADON tb_CHITIETHOADON { get; set; }
    }
}
