//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcmMobileShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HANGSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_HANGSP()
        {
            this.tb_SANPHAM = new HashSet<tb_SANPHAM>();
        }
    
        public int IdHangSP { get; set; }
        public string TenHangSP { get; set; }
        public bool TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SANPHAM> tb_SANPHAM { get; set; }
    }
}
