//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcmMobileShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_SANPHAM()
        {
            this.tb_BannerSP = new HashSet<tb_BannerSP>();
            this.tb_CT_SANPHAM = new HashSet<tb_CT_SANPHAM>();
            this.tb_DISCOUNTSP = new HashSet<tb_DISCOUNTSP>();
        }
    
        public int IdSP { get; set; }
        public Nullable<int> IdHangSP { get; set; }
        public Nullable<int> IdLoaiSP { get; set; }
        public string TenSP { get; set; }
        public string MoTaSP { get; set; }
        public Nullable<double> Gia { get; set; }
        public string ImagePathMain { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public bool TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BannerSP> tb_BannerSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CT_SANPHAM> tb_CT_SANPHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_DISCOUNTSP> tb_DISCOUNTSP { get; set; }
        public virtual tb_HANGSP tb_HANGSP { get; set; }
        public virtual tb_LOAISP tb_LOAISP { get; set; }
    }
}
